import {
  UserProfile,
  DocumentItem,
  TenderDetail,
  BidItem,
  ClarificationItem,
  RequirementAuditItem,
} from '@/types/user';

export const initialProfile: UserProfile = {
  companyName: 'ABC Technologies & Engineering Ltd',
  tradeName: 'TechCorp Solutions',
  companyType: 'Public Limited Company',
  cin: 'U29100TN2015PLC098765',
  pan: 'AAACA1234F',
  gstin: '33AAACA1234F1ZV',
  udyam: 'UDYAM-TN-02-0019283',
  epfoCode: 'TNMAS0029182000',
  registeredAddress: {
    line1: 'Plot No. 45, Guindy Industrial Estate',
    line2: 'Phase II, Inner Ring Road',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600032',
    country: 'India',
  },
  authorizedSignatory: {
    name: 'R. Ramanathan',
    designation: 'Managing Director & CEO',
    email: 'compliance@abctech.in',
    phone: '+91 98765 43210',
    dinOrDsc: 'DIN-00892147 / DSC-CLASS3-2026',
  },
  bankDetails: {
    accountName: 'ABC Technologies & Engineering Ltd - Escrow',
    accountNumber: '920020048911029',
    ifsc: 'SBIN0001024',
    bankName: 'State Bank of India',
    branch: 'Industrial Finance Branch, Chennai',
  },
  verifications: [
    { type: 'GSTN', status: 'ACTIVE', latencyMs: 45, lastChecked: '24 Aug 2026 10:30 IST' },
    { type: 'NSDL', status: 'VERIFIED', latencyMs: 112, lastChecked: '24 Aug 2026 10:30 IST' },
    { type: 'UDYAM', status: 'VERIFIED', latencyMs: 80, lastChecked: '24 Aug 2026 10:31 IST' },
    { type: 'ICAI_UDIN', status: 'VERIFIED', latencyMs: 95, lastChecked: '24 Aug 2026 10:31 IST' },
  ],
};

export const initialDocuments: DocumentItem[] = [
  {
    id: 'doc-gstn',
    name: 'GST_Registration_Certificate_Form_REG-06.pdf',
    category: 'Statutory / Tax',
    docNumber: '33AAACA1234F1ZV',
    uploadedAt: '12 Jan 2026',
    expiryDate: 'Perpetual',
    status: 'VERIFIED',
    source: 'Direct GSTN Gateway',
    confidence: 100,
    fileSize: '1.4 MB',
    fileType: 'pdf',
    hashSha256: 'SHA256:8f4b23a1c9e7829d3f10ba8942ce1198',
    extractedFields: [
      { label: 'Legal Name', value: 'ABC Technologies & Engineering Ltd', confidence: 100 },
      { label: 'GSTIN', value: '33AAACA1234F1ZV', confidence: 100 },
      { label: 'Taxpayer Type', value: 'Regular', confidence: 100 },
      { label: 'Registration Date', value: '01/07/2017', confidence: 99 },
    ],
  },
  {
    id: 'doc-pan',
    name: 'Permanent_Account_Number_PAN_Card.pdf',
    category: 'Statutory / Tax',
    docNumber: 'AAACA1234F',
    uploadedAt: '12 Jan 2026',
    expiryDate: 'Perpetual',
    status: 'VERIFIED',
    source: 'NSDL Database',
    confidence: 99,
    fileSize: '780 KB',
    fileType: 'pdf',
    hashSha256: 'SHA256:3d10c28fa719e0b88492019ab921cba1',
    extractedFields: [
      { label: 'Entity Name', value: 'ABC TECHNOLOGIES & ENGINEERING LTD', confidence: 99 },
      { label: 'PAN', value: 'AAACA1234F', confidence: 100 },
      { label: 'Category', value: 'Company (C)', confidence: 100 },
    ],
  },
  {
    id: 'doc-turnover',
    name: 'CA_Audited_Turnover_NetWorth_FY25.pdf',
    category: 'Financial / Audit',
    docNumber: 'UDIN-26034182AAAA9912',
    uploadedAt: '18 Aug 2026',
    expiryDate: '31 Mar 2027',
    status: 'VERIFIED',
    source: 'ICAI UDIN Registry',
    confidence: 100,
    fileSize: '3.2 MB',
    fileType: 'pdf',
    hashSha256: 'SHA256:a9108b23c91e8472910fa8932cde1209',
    extractedFields: [
      { label: '3-Year Average Turnover', value: '₹ 14.80 Crore', confidence: 100 },
      { label: 'Positive Net Worth', value: '₹ 22.45 Crore', confidence: 99 },
      { label: 'UDIN', value: 'UDIN-26034182AAAA9912', confidence: 100 },
      { label: 'CA Firm Name', value: 'M/s S. Sundaram & Co (FRN: 001928S)', confidence: 98 },
    ],
  },
  {
    id: 'doc-oem',
    name: 'OEM_Authorization_Letter_Emerson.pdf',
    category: 'Technical / OEM',
    docNumber: 'OEM/2024/VALV-89',
    uploadedAt: '04 Feb 2026',
    expiryDate: '31 Mar 2025',
    status: 'EXPIRED',
    source: 'AI OCR Parser',
    confidence: 91,
    fileSize: '1.1 MB',
    fileType: 'pdf',
    hashSha256: 'SHA256:55ab9102c31e98471928bcad90123ef4',
    extractedFields: [
      { label: 'Manufacturer Name', value: 'Emerson Process Management Asia', confidence: 94 },
      { label: 'Authorized Territory', value: 'India - Southern Region', confidence: 92 },
      { label: 'Validity Period', value: '01 Apr 2024 to 31 Mar 2025 (EXPIRED)', confidence: 96 },
    ],
  },
  {
    id: 'doc-mii',
    name: 'Make_In_India_Local_Content_Declaration.pdf',
    category: 'Compliance / MII',
    docNumber: 'MII-DECL-2026-08',
    uploadedAt: '20 Aug 2026',
    expiryDate: '31 Dec 2026',
    status: 'REVIEW_REQUIRED',
    source: 'AI Regex Engine',
    confidence: 98,
    fileSize: '950 KB',
    fileType: 'pdf',
    hashSha256: 'SHA256:ee849102bc9102837461902837461902',
    extractedFields: [
      { label: 'Declared Local Content', value: '42.00% (Class-II Supplier)', confidence: 98 },
      { label: 'Manufacturing Facility', value: 'Plot 44, Electronic City, Phase II, Bangalore', confidence: 95 },
      { label: 'Class Category', value: 'Class-II Local Supplier (Threshold Gap for Class-I)', confidence: 99 },
    ],
  },
  {
    id: 'doc-iso',
    name: 'ISO_27001_Information_Security_Cert.pdf',
    category: 'Security / ISO',
    docNumber: 'CERT-ISO-991A',
    uploadedAt: '15 Nov 2023',
    expiryDate: '06 Sep 2026',
    status: 'REVIEW_REQUIRED',
    source: 'TUV Nord Database',
    confidence: 95,
    fileSize: '1.8 MB',
    fileType: 'pdf',
    hashSha256: 'SHA256:1092837465abcde1092837465abcde1',
    extractedFields: [
      { label: 'Standard', value: 'ISO/IEC 27001:2022', confidence: 98 },
      { label: 'Expiry Date', value: '06 Sep 2026 (12 days remaining)', confidence: 96 },
      { label: 'Accreditation Body', value: 'NABCB / IAF', confidence: 97 },
    ],
  },
  {
    id: 'doc-udyam',
    name: 'Udyam_Registration_Certificate_MSME.pdf',
    category: 'Statutory / MSME',
    docNumber: 'UDYAM-TN-02-0019283',
    uploadedAt: '05 Jan 2026',
    expiryDate: 'Perpetual',
    status: 'VERIFIED',
    source: 'MSME Sandbox Gateway',
    confidence: 99,
    fileSize: '820 KB',
    fileType: 'pdf',
    hashSha256: 'SHA256:aa918237461902837461902837461902',
    extractedFields: [
      { label: 'Enterprise Type', value: 'Medium Enterprise (Manufacturing)', confidence: 100 },
      { label: 'Major Activity', value: 'Manufacture of industrial process control equipment', confidence: 97 },
    ],
  },
  {
    id: 'doc-exp',
    name: 'Past_Performance_Record_CPCL_IOCL.pdf',
    category: 'Technical / Experience',
    docNumber: 'EXP-IND-4091',
    uploadedAt: '10 Aug 2026',
    expiryDate: 'Perpetual',
    status: 'VERIFIED',
    source: 'AI Semantic Matcher',
    confidence: 98,
    fileSize: '4.5 MB',
    fileType: 'pdf',
    hashSha256: 'SHA256:bb827364519283746519283746519283',
    extractedFields: [
      { label: 'Completed PSU Contracts', value: '5 Major Refineries in last 3 Years', confidence: 98 },
      { label: 'Cumulative Order Value', value: '₹ 38.60 Crore', confidence: 97 },
    ],
  },
];

export const initialComplianceRules = [
  { ruleId: 'REQ-STAT-01', category: 'Statutory' as const, title: 'Valid GSTIN Registration', tenderRequirement: 'Active Regular GSTIN with 100% GSTR-3B compliance', isMandatory: true, clauseReference: 'Section 3.1 (a)' },
  { ruleId: 'REQ-STAT-02', category: 'Statutory' as const, title: 'Permanent Account Number (PAN)', tenderRequirement: 'Company entity PAN registered with Income Tax Department', isMandatory: true, clauseReference: 'Section 3.1 (b)' },
  { ruleId: 'REQ-STAT-03', category: 'Statutory' as const, title: 'MSME / Udyam Certificate', tenderRequirement: 'Valid Udyam Registration for EMD Exemption eligibility', isMandatory: false, clauseReference: 'Section 3.2' },
  { ruleId: 'REQ-FIN-01', category: 'Financial' as const, title: 'Minimum Annual Turnover', tenderRequirement: 'Average annual financial turnover ≥ ₹ 10.00 Cr in last 3 FYs', isMandatory: true, clauseReference: 'Section 4.1' },
  { ruleId: 'REQ-FIN-02', category: 'Financial' as const, title: 'Positive Net Worth', tenderRequirement: 'Audited balance sheet showing positive net worth as of March 2025', isMandatory: true, clauseReference: 'Section 4.2' },
  { ruleId: 'REQ-FIN-03', category: 'Financial' as const, title: 'Solvency Certificate', tenderRequirement: 'Bank Solvency certificate of at least ₹ 4.00 Cr', isMandatory: true, clauseReference: 'Section 4.3' },
  { ruleId: 'REQ-TECH-01', category: 'Technical' as const, title: 'Past Performance in Process Instrumentation', tenderRequirement: 'Executed at least 3 similar contracts for PSU refineries', isMandatory: true, clauseReference: 'Section 5.1' },
  { ruleId: 'REQ-TECH-02', category: 'Technical' as const, title: 'Single Order Value Threshold', tenderRequirement: 'Single work order value not less than ₹ 5.80 Cr (40% of est.)', isMandatory: true, clauseReference: 'Section 5.2' },
  { ruleId: 'REQ-TECH-03', category: 'Technical' as const, title: 'OEM Authorization Letter', tenderRequirement: 'Direct manufacturer authorization covering full warranty period (FY26-28)', isMandatory: true, clauseReference: 'Section 5.4' },
  { ruleId: 'REQ-LC-01', category: 'Local Content' as const, title: 'Make-in-India Class-I Supplier Preference', tenderRequirement: 'Local content percentage ≥ 50% to claim Class-I purchase preference', isMandatory: true, clauseReference: 'PPO-2020 Order' },
  { ruleId: 'REQ-SEC-01', category: 'Technical' as const, title: 'Information Security ISO 27001', tenderRequirement: 'Valid ISO/IEC 27001 certificate at the time of bid closing', isMandatory: true, clauseReference: 'Section 6.2' },
  { ruleId: 'REQ-LEGAL-01', category: 'Legal' as const, title: 'Non-Blacklisting Undertaking', tenderRequirement: 'Self-declaration on stamp paper stating no debarment by GeM/CVC', isMandatory: true, clauseReference: 'Section 7.1' },
  { ruleId: 'REQ-LEGAL-02', category: 'Legal' as const, title: 'Land Border Compliance (Rule 144(xi))', tenderRequirement: 'Declaration regarding countries sharing land border with India', isMandatory: true, clauseReference: 'OM F.No.6/18/2019-PPD' },
  { ruleId: 'REQ-STAT-04', category: 'Statutory' as const, title: 'EPFO & ESIC Registration', tenderRequirement: 'Active EPFO code with continuous contribution proof', isMandatory: true, clauseReference: 'Section 3.4' },
];

export const initialTenders: TenderDetail[] = [
  {
    id: 'GEM-2026-B-1024',
    tenderNumber: 'GEM/2026/B/1024',
    title: 'Data Center Migration, SCADA Integration & Zero-Trust Security Upgrade',
    organization: 'Chennai Petroleum Corporation Limited (CPCL)',
    department: 'Instrumentation, Electrical & Cyber Defense Group',
    category: 'IT Services & Industrial EPC',
    estimatedValueINR: 145000000,
    estimatedValueFormatted: '₹ 14.50 Cr',
    closingDate: '28 Aug 2026, 17:00 IST',
    daysLeft: 4,
    location: 'Manali Refinery Complex, Chennai, Tamil Nadu',
    matchScore: 86,
    complianceRuleCount: 24,
    status: 'OPEN',
    tags: ['Class-I MII Preferred', 'EMD Exempt for MSE', 'High Priority', 'Turnkey EPC'],
    emdAmountFormatted: '₹ 29.00 Lakh (Exempt for MSE)',
    publishingDate: '01 Aug 2026',
    description:
      'Complete modernization of refinery industrial SCADA control systems, distributed high-pressure instrumentation telemetry, cloud containerized workload migration, and deployment of zero-trust microsegmentation architecture.',
    scopeOfWork: [
      'Supply and calibration of 450+ smart SIL-3 rated pressure and differential telemetry transmitters.',
      'Integration with central Emerson DeltaV DCS and redundant SCADA telemetry backbone.',
      'Deployment of hardware security modules (HSM) and zero-trust gateway access controllers.',
      '24x7 Comprehensive On-site AMC and operational maintenance for 36 months.',
    ],
    eligibilityCriteria: [
      'Registered enterprise in India with active GSTIN and regular tax filings for 3 years.',
      'Average financial turnover of minimum ₹ 10.00 Cr in the last 3 financial years.',
      'Successful execution of at least 3 industrial instrumentation projects for CPSEs/PSUs.',
      'Valid OEM Authorization from approved transmitter and DCS manufacturers.',
      'Make-in-India Local Content requirement of ≥ 50% for Class-I Local Supplier preference.',
    ],
    boqItems: [
      { itemNo: 1, itemDescription: 'Smart High-Pressure Transmitter SIL-3 rated', quantity: 280, uom: 'NOS', estimatedRate: 185000 },
      { itemNo: 2, itemDescription: 'SCADA Telemetry Controller Gateway Module', quantity: 45, uom: 'NOS', estimatedRate: 420000 },
      { itemNo: 3, itemDescription: 'Zero-Trust Cyber Gateway & IDS/IPS Appliance', quantity: 12, uom: 'SETS', estimatedRate: 1250000 },
      { itemNo: 4, itemDescription: 'Turnkey Installation, Testing & 3-Year AMC', quantity: 1, uom: 'LOT', estimatedRate: 23500000 },
    ],
    complianceRules: initialComplianceRules,
    officerInCharge: {
      name: 'P. Sharma, DGM (Procurement)',
      designation: 'Deputy General Manager (Contracts & Materials)',
      department: 'Central Procurement Bureau, CPCL',
    },
  },
  {
    id: 'GEM-2026-C-8812',
    tenderNumber: 'GEM/2026/C/8812',
    title: 'Regional Transit Hub SCADA Telemetry & Intelligent Commuter Infrastructure',
    organization: 'Metro Transit Authority (CMRL)',
    department: 'Signalling, Telecommunications & Power Bureau',
    category: 'Smart Mobility & Telemetry',
    estimatedValueINR: 380000000,
    estimatedValueFormatted: '₹ 38.00 Cr',
    closingDate: '15 Sep 2026, 15:00 IST',
    daysLeft: 22,
    location: 'Sector 4 Metro Depot, Chennai, Tamil Nadu',
    matchScore: 94,
    complianceRuleCount: 28,
    status: 'OPEN',
    tags: ['Infrastructure', 'Global Tender Enquiry', 'Smart City'],
    emdAmountFormatted: '₹ 76.00 Lakh',
    publishingDate: '10 Aug 2026',
    description:
      'Turnkey delivery of automated supervisory control, traction power SCADA telemetry, environmental monitoring stations, and centralized command center displays.',
    scopeOfWork: [
      'Design, manufacture, supply, and testing of SCADA RTUs across 18 stations.',
      'Fiber optic redundant network ring deployment and sub-station automation.',
      'Integration with unified transit operations control center (OCC).',
    ],
    eligibilityCriteria: [
      'Consortium or Single Bidder with ₹ 25 Cr+ annual turnover.',
      'Proven experience in metro rail or high-speed transit telemetry in India.',
    ],
    boqItems: [
      { itemNo: 1, itemDescription: 'Traction Power RTU Unit', quantity: 36, uom: 'NOS', estimatedRate: 650000 },
      { itemNo: 2, itemDescription: 'OCC Server Infrastructure Cluster', quantity: 4, uom: 'SETS', estimatedRate: 18000000 },
    ],
    complianceRules: initialComplianceRules,
    officerInCharge: {
      name: 'K. Ananthapadmanabhan',
      designation: 'Chief General Manager (Signalling)',
      department: 'Metro Rail Operations',
    },
  },
  {
    id: 'IOCL-ENG-2026-89',
    tenderNumber: 'IOCL/ENG/2026/89',
    title: 'Supply, Installation & Commissioning of SCADA Telemetry Modules',
    organization: 'Indian Oil Corporation Limited (IOCL)',
    department: 'Pipelines Division, Southern Region',
    category: 'Industrial Automation',
    estimatedValueINR: 82000000,
    estimatedValueFormatted: '₹ 8.20 Cr',
    closingDate: '30 Aug 2026, 18:00 IST',
    daysLeft: 6,
    location: 'Ennore Coastal Terminal, Tamil Nadu',
    matchScore: 95,
    complianceRuleCount: 20,
    status: 'OPEN',
    tags: ['IOCL Pipelines', 'Automation', 'Fast Track'],
    emdAmountFormatted: '₹ 16.40 Lakh',
    publishingDate: '05 Aug 2026',
    description:
      'Supply of explosion-proof field telemetry units, solar power telemetry pods, and integration with IOCL master pipelines SCADA host.',
    scopeOfWork: [
      'Supply of 120 Field SCADA Telemetry Modules.',
      'Installation at remote valve stations along Chennai-Tiruchirappalli pipeline.',
    ],
    eligibilityCriteria: [
      'Experience in hydrocarbon pipeline instrumentation.',
      'Valid PESO / ATEX certificates for hazardous area deployment.',
    ],
    boqItems: [
      { itemNo: 1, itemDescription: 'Ex-Proof Telemetry Pod', quantity: 120, uom: 'NOS', estimatedRate: 550000 },
    ],
    complianceRules: initialComplianceRules,
    officerInCharge: {
      name: 'V. S. Raghavan',
      designation: 'Senior Manager (Pipeline Telemetry)',
      department: 'IOCL Pipelines Division',
    },
  },
];

export const initialBids: BidItem[] = [
  {
    id: 'bid-cpcl-1024',
    bidId: 'BID-2026-1024',
    tenderId: 'GEM-2026-B-1024',
    tenderNumber: 'GEM/2026/B/1024',
    tenderTitle: 'Data Center Migration, SCADA Integration & Zero-Trust Upgrade',
    organization: 'Chennai Petroleum Corporation Limited (CPCL)',
    quotedValueINR: 138500000,
    quotedValueFormatted: '₹ 13.85 Cr',
    priceBreakdown: {
      basicRateINR: 117372881,
      gstPercentage: 18,
      gstAmountINR: 21127119,
      freightAndInstallationINR: 0,
      totalQuotedINR: 138500000,
      totalQuotedFormatted: '₹ 13.85 Cr',
    },
    status: 'CLARIFICATION_REQUIRED',
    complianceScore: 82,
    riskLevel: 'MEDIUM',
    submittedAt: '22 Aug 2026 14:15 IST',
    sealedEnvelopeHash: 'SHA256:7f89bc10293847561029384756102938',
    auditTimeline: [
      { stageNumber: 1, title: 'Bid Sealed & Submitted', status: 'COMPLETED', timestamp: '22 Aug 2026 14:15 IST', description: 'SHA-256 Envelope hash generated and locked on GeM portal.', completedBy: 'Bidder System' },
      { stageNumber: 2, title: 'OCR & Cryptographic Extraction', status: 'COMPLETED', timestamp: '22 Aug 2026 14:18 IST', description: 'Govt API gateways verified GSTN, NSDL, and ICAI UDIN entries in 280ms.', completedBy: 'AI Gateway Service' },
      { stageNumber: 3, title: 'Deterministic Compliance Evaluation', status: 'COMPLETED', timestamp: '22 Aug 2026 14:22 IST', description: '24 rules evaluated: 18 PASS, 2 REVIEW, 1 CRITICAL FLAG (OEM validity).', completedBy: 'Rule Engine v4.2' },
      { stageNumber: 4, title: 'Officer Clarification Query', status: 'IN_PROGRESS', timestamp: '24 Aug 2026 09:40 IST', description: 'Procurement Officer raised technical query regarding OEM certificate date.', completedBy: 'P. Sharma (CPCL Officer)' },
      { stageNumber: 5, title: 'Final Determination & Award', status: 'PENDING', description: 'Awaiting bidder clarification response and committee final verdict.' },
    ],
    auditSummary: {
      passedRules: 18,
      reviewRules: 2,
      failedRules: 1,
      totalRules: 24,
    },
    auditMatrix: [
      { ruleId: 'REQ-STAT-01', category: 'Statutory', title: 'Valid GSTIN Registration', tenderRequirement: 'Active Regular GSTIN', bidderExtractedValue: '33AAACA1234F1ZV (Active Regular)', status: 'PASS', confidence: 100, sourceDocName: 'GST_Registration_Certificate_Form_REG-06.pdf', notes: 'Verified via GSTN Gateway (45ms)' },
      { ruleId: 'REQ-STAT-02', category: 'Statutory', title: 'PAN Card Validation', tenderRequirement: 'Company PAN registered with IT Dept', bidderExtractedValue: 'AAACA1234F (Verified)', status: 'PASS', confidence: 99, sourceDocName: 'Permanent_Account_Number_PAN_Card.pdf', notes: 'Verified via NSDL Database (112ms)' },
      { ruleId: 'REQ-FIN-01', category: 'Financial', title: 'Average 3-Yr Financial Turnover', tenderRequirement: '≥ ₹ 10.00 Cr 3-Yr Avg', bidderExtractedValue: '₹ 14.80 Cr (CA Audited)', status: 'PASS', confidence: 100, sourceDocName: 'CA_Audited_Turnover_NetWorth_FY25.pdf', notes: 'Verified via ICAI UDIN Registry' },
      { ruleId: 'REQ-FIN-02', category: 'Financial', title: 'Positive Net Worth', tenderRequirement: 'Net Worth > 0', bidderExtractedValue: '₹ 22.45 Cr Positive Net Worth', status: 'PASS', confidence: 100, sourceDocName: 'CA_Audited_Turnover_NetWorth_FY25.pdf', notes: 'Certified by S. Sundaram & Co' },
      { ruleId: 'REQ-TECH-03', category: 'Technical', title: 'OEM Authorization Letter', tenderRequirement: 'Valid for FY2026-28', bidderExtractedValue: 'Expired 31 Mar 2025 in uploaded document', status: 'FAIL', confidence: 96, sourceDocName: 'OEM_Authorization_Letter_Emerson.pdf', evidenceLocation: 'Page 1, Paragraph 3', notes: 'CRITICAL FLAG: Date expired. Clarification issued.' },
      { ruleId: 'REQ-LC-01', category: 'Local Content', title: 'Make-in-India Local Content %', tenderRequirement: '≥ 50% for Class-I Preference', bidderExtractedValue: '42.00% (Class-II Supplier)', status: 'REVIEW', confidence: 98, sourceDocName: 'Make_In_India_Local_Content_Declaration.pdf', evidenceLocation: 'Page 1, Item 2', notes: 'Bidder meets Class-II (42%) but falls short of Class-I preference threshold.' },
      { ruleId: 'REQ-SEC-01', category: 'Technical', title: 'ISO 27001 Security Certification', tenderRequirement: 'Valid ISO 27001:2022', bidderExtractedValue: 'CERT-ISO-991A (Expires 06 Sep 2026)', status: 'REVIEW', confidence: 95, sourceDocName: 'ISO_27001_Information_Security_Cert.pdf', notes: 'Valid at bid opening, but renewal required within 12 days.' },
      { ruleId: 'REQ-LEGAL-01', category: 'Legal', title: 'Non-Blacklisting Declaration', tenderRequirement: 'Signed Integrity Pledge', bidderExtractedValue: 'Signed by R. Ramanathan, MD', status: 'PASS', confidence: 99, notes: 'DSC Signature Valid' },
    ],
    attachedDocIds: ['doc-gstn', 'doc-pan', 'doc-turnover', 'doc-oem', 'doc-mii', 'doc-iso', 'doc-udyam', 'doc-exp'],
  },
  {
    id: 'bid-iocl-0982',
    bidId: 'BID-2026-0982',
    tenderId: 'IOCL-ENG-2026-89',
    tenderNumber: 'IOCL/ENG/2026/89',
    tenderTitle: 'Supply, Installation & Commissioning of SCADA Telemetry Modules',
    organization: 'Indian Oil Corporation Limited (IOCL)',
    quotedValueINR: 79500000,
    quotedValueFormatted: '₹ 7.95 Cr',
    priceBreakdown: {
      basicRateINR: 67372881,
      gstPercentage: 18,
      gstAmountINR: 12127119,
      freightAndInstallationINR: 0,
      totalQuotedINR: 79500000,
      totalQuotedFormatted: '₹ 7.95 Cr',
    },
    status: 'UNDER_EVALUATION',
    complianceScore: 95,
    riskLevel: 'LOW',
    submittedAt: '20 Aug 2026 11:30 IST',
    sealedEnvelopeHash: 'SHA256:1192837465abcde1092837465abcde2',
    auditTimeline: [
      { stageNumber: 1, title: 'Bid Sealed & Submitted', status: 'COMPLETED', timestamp: '20 Aug 2026 11:30 IST', description: 'Encrypted and locked on GeM portal.', completedBy: 'Bidder System' },
      { stageNumber: 2, title: 'OCR & Statutory Verification', status: 'COMPLETED', timestamp: '20 Aug 2026 11:32 IST', description: 'All statutory records verified with 100% confidence.', completedBy: 'AI Gateway' },
      { stageNumber: 3, title: 'Compliance Rule Matrix', status: 'COMPLETED', timestamp: '20 Aug 2026 11:35 IST', description: '19 PASS, 1 Minor Review. High compliance integrity.', completedBy: 'AI Engine' },
      { stageNumber: 4, title: 'Technical Committee Evaluation', status: 'IN_PROGRESS', timestamp: '23 Aug 2026 16:00 IST', description: 'Commercial & technical committee reviewing bid price & BOQ schedule.', completedBy: 'IOCL Tender Committee' },
      { stageNumber: 5, title: 'Final Award', status: 'PENDING', description: 'Commercial envelope opening scheduled for 31 Aug 2026.' },
    ],
    auditSummary: {
      passedRules: 19,
      reviewRules: 1,
      failedRules: 0,
      totalRules: 20,
    },
    auditMatrix: [
      { ruleId: 'REQ-STAT-01', category: 'Statutory', title: 'Valid GSTIN Registration', tenderRequirement: 'Active Regular GSTIN', bidderExtractedValue: '33AAACA1234F1ZV (Active)', status: 'PASS', confidence: 100, sourceDocName: 'GST_Registration_Certificate_Form_REG-06.pdf' },
      { ruleId: 'REQ-FIN-01', category: 'Financial', title: 'Turnover Requirement', tenderRequirement: '≥ ₹ 5.00 Cr', bidderExtractedValue: '₹ 14.80 Cr (CA Audited)', status: 'PASS', confidence: 100, sourceDocName: 'CA_Audited_Turnover_NetWorth_FY25.pdf' },
      { ruleId: 'REQ-TECH-01', category: 'Technical', title: 'PESO / Flameproof Certification', tenderRequirement: 'PESO approved enclosure', bidderExtractedValue: 'Certificate PESO/S/2024/991 Attached', status: 'PASS', confidence: 97 },
    ],
    attachedDocIds: ['doc-gstn', 'doc-pan', 'doc-turnover', 'doc-udyam', 'doc-exp'],
  },
  {
    id: 'bid-cmrl-0744',
    bidId: 'BID-2026-0744',
    tenderId: 'GEM-2026-C-8812',
    tenderNumber: 'GEM/2026/C/8812',
    tenderTitle: 'Regional Transit Hub SCADA Telemetry & Intelligent Commuter Infrastructure',
    organization: 'Metro Transit Authority (CMRL)',
    quotedValueINR: 358000000,
    quotedValueFormatted: '₹ 35.80 Cr',
    priceBreakdown: {
      basicRateINR: 303389830,
      gstPercentage: 18,
      gstAmountINR: 54610170,
      freightAndInstallationINR: 0,
      totalQuotedINR: 358000000,
      totalQuotedFormatted: '₹ 35.80 Cr',
    },
    status: 'SUBMITTED',
    complianceScore: 91,
    riskLevel: 'LOW',
    submittedAt: '24 Aug 2026 09:10 IST',
    sealedEnvelopeHash: 'SHA256:8899aabbccddeeff0011223344556677',
    auditTimeline: [
      { stageNumber: 1, title: 'Bid Sealed & Submitted', status: 'COMPLETED', timestamp: '24 Aug 2026 09:10 IST', description: 'Sealed with DSC Level 3 signature.', completedBy: 'Bidder System' },
      { stageNumber: 2, title: 'AI Extraction & Gateways', status: 'COMPLETED', timestamp: '24 Aug 2026 09:12 IST', description: 'Cross-verified against MCA and GSTN.', completedBy: 'AI Gateway' },
      { stageNumber: 3, title: 'Compliance Rule Matrix', status: 'COMPLETED', timestamp: '24 Aug 2026 09:15 IST', description: '22 PASS, 2 REVIEW.', completedBy: 'AI Engine' },
      { stageNumber: 4, title: 'Committee Technical Evaluation', status: 'PENDING', description: 'Pending bid submission closing date (15 Sep 2026).' },
      { stageNumber: 5, title: 'Final Determination', status: 'PENDING', description: 'Awaiting technical opening.' },
    ],
    auditSummary: {
      passedRules: 22,
      reviewRules: 2,
      failedRules: 0,
      totalRules: 24,
    },
    auditMatrix: [
      { ruleId: 'REQ-STAT-01', category: 'Statutory', title: 'Valid GSTIN Registration', tenderRequirement: 'Active Regular GSTIN', bidderExtractedValue: '33AAACA1234F1ZV (Active)', status: 'PASS', confidence: 100 },
      { ruleId: 'REQ-FIN-01', category: 'Financial', title: 'Annual Turnover', tenderRequirement: '≥ ₹ 25.00 Cr', bidderExtractedValue: '₹ 14.80 Cr (Consortium Partner: ₹ 42.00 Cr)', status: 'PASS', confidence: 96 },
    ],
    attachedDocIds: ['doc-gstn', 'doc-pan', 'doc-turnover', 'doc-udyam', 'doc-exp', 'doc-iso'],
  },
];

export const initialClarifications: ClarificationItem[] = [
  {
    id: 'clar-cpcl-01',
    bidId: 'BID-2026-1024',
    tenderNumber: 'GEM/2026/B/1024',
    tenderTitle: 'Data Center Migration, SCADA Integration & Zero-Trust Security Upgrade',
    organization: 'Chennai Petroleum Corporation Limited (CPCL)',
    officerName: 'P. Sharma (DGM Contracts & Materials)',
    queryTitle: 'Discrepancy in OEM Authorization Letter Expiry Date (Rule REQ-TECH-03)',
    queryDetails:
      'Upon AI-assisted compliance parsing of your technical bid submission for Tender GEM/2026/B/1024, the uploaded OEM Authorization certificate from Emerson Process Management (Doc ID: OEM/2024/VALV-89) indicates validity expired on 31 March 2025. In terms of Clause 5.4 of the Technical Bid Specifications, the bidder must possess an active, unexpired manufacturer authorization covering the 36-month AMC execution period. Please furnish a renewed OEM certificate valid through FY 2026-2028 or clarify if a direct parent warranty applies.',
    queryRaisedAt: '24 Aug 2026 09:40 IST',
    deadlineDate: '27 Aug 2026, 17:00 IST (3 Days Remaining)',
    status: 'PENDING',
    flaggedRuleId: 'REQ-TECH-03',
    flaggedDocName: 'OEM_Authorization_Letter_Emerson.pdf',
    bidderResponse: undefined,
  },
];
