import { Tender, Bidder } from '@/types';

export const mockTenders: Tender[] = [
  {
    id: "T-1024",
    tenderNumber: "CPCL/2026/1024",
    title: "Procurement of High-Pressure Pipeline Instrumentation & Control Units",
    organization: "Chennai Petroleum Corporation Limited (CPCL)",
    category: "Industrial Equipment & EPC",
    estimatedValue: "₹ 14.50 Cr",
    publishedDate: "15 Aug 2026",
    closingDate: "28 Aug 2026",
    status: "LIVE",
    requirementsCount: 24,
    bidsCount: 5,
    assignedOfficer: "Dr. Rajeshwar Sharma",
    department: "Instrumentation & Control"
  },
  {
    id: "T-1031",
    tenderNumber: "IOCL/ENG/2026/89",
    title: "Supply, Installation & Commissioning of SCADA Telemetry Modules",
    organization: "Indian Oil Corporation Ltd",
    category: "Automation & Telemetry",
    estimatedValue: "₹ 8.20 Cr",
    publishedDate: "10 Aug 2026",
    closingDate: "25 Aug 2026",
    status: "UNDER_EVALUATION",
    requirementsCount: 18,
    bidsCount: 7,
    assignedOfficer: "Pooja Ananthakrishnan",
    department: "Northern Region Pipelines"
  },
  {
    id: "T-1045",
    tenderNumber: "ONGC/OFFSHORE/2026/112",
    title: "Deepwater Subsea High-Pressure Gate & Choke Valves Package",
    organization: "Oil and Natural Gas Corporation",
    category: "Offshore Mechanical",
    estimatedValue: "₹ 46.80 Cr",
    publishedDate: "01 Aug 2026",
    closingDate: "05 Sep 2026",
    status: "LIVE",
    requirementsCount: 32,
    bidsCount: 4,
    assignedOfficer: "Ashok Verma",
    department: "Western Offshore Basin"
  },
  {
    id: "T-1052",
    tenderNumber: "BHEL/RAN/2026/04",
    title: "Supply of Heavy Forged Boiler Components & Pressure Flanges",
    organization: "Bharat Heavy Electricals Limited",
    category: "Heavy Metallurgy",
    estimatedValue: "₹ 22.40 Cr",
    publishedDate: "20 Jul 2026",
    closingDate: "18 Aug 2026",
    status: "CLOSED",
    requirementsCount: 20,
    bidsCount: 6,
    assignedOfficer: "T. Natarajan",
    department: "Boiler Auxiliaries Plant"
  },
  {
    id: "T-1060",
    tenderNumber: "DRDO/DMM/2026/902",
    title: "Precision Sensor Arrays & EMI Shielded Rugged Telemetry Housings",
    organization: "Defence Research & Development Organisation",
    category: "Defence Electronics",
    estimatedValue: "₹ 19.10 Cr",
    publishedDate: "18 Aug 2026",
    closingDate: "15 Sep 2026",
    status: "LIVE",
    requirementsCount: 28,
    bidsCount: 3,
    assignedOfficer: "Dr. Rajeshwar Sharma",
    department: "Material Management"
  }
];

export const mockBidders: Bidder[] = [
  {
    id: "B-101",
    bidId: "BID-2026-1024",
    name: "ABC Technologies & Engineering Ltd",
    pan: "AAACA1234F",
    gstin: "33AAACA1234F1ZV",
    udyam: "UDYAM-TN-02-0019283",
    submittedAt: "24 Aug 2026, 18:42",
    complianceScore: 82,
    riskLevel: "MEDIUM",
    status: "CLARIFICATION_REQUIRED",
    financialBid: "₹ 13.85 Cr",
    localContentPercent: 42,
    tenderId: "T-1024",
    tenderNumber: "CPCL/2026/1024",
    organization: "Chennai Petroleum Corporation Limited",
    requirements: [
      {
        id: "req-1",
        name: "Local Content (Make-in-India)",
        category: "Make-in-India",
        expected: "≥ 50.0%",
        extracted: "42.0%",
        difference: "-8.0%",
        status: "FAIL",
        risk: "HIGH",
        confidence: 98,
        sourceDoc: "Make-in-India_Self_Declaration.pdf",
        page: 4,
        snippet: "We hereby confirm our local manufacturing content value addition is 42% for the quoted pipeline units.",
        aiExplanation: "The tender strictly mandates minimum 50% Class-I Local Supplier status. The declaration states only 42% local content, leading to non-compliance."
      },
      {
        id: "req-2",
        name: "OEM Authorization & Warranty Commitment",
        category: "Technical",
        expected: "Valid OEM Letter for FY26-27 with min 3-yr warranty",
        extracted: "OEM Letter dated June 2024 (Expired FY25 scope)",
        difference: "Expired Authorization Scope",
        status: "REVIEW",
        risk: "MEDIUM",
        confidence: 91,
        sourceDoc: "OEM_Authorization_Certificate.pdf",
        page: 2,
        snippet: "Authorized partner valid through 31st March 2025 across western territory.",
        aiExplanation: "Authorization scope expired on March 2025 and territory specifies western zone instead of southern refineries."
      },
      {
        id: "req-3",
        name: "GSTIN Status & Filing Consistency",
        category: "Statutory",
        expected: "Active & 3B filed up to July 2026",
        extracted: "Active, Regular, Zero default",
        status: "PASS",
        risk: "LOW",
        confidence: 100,
        sourceDoc: "GST_API_Verification",
        page: 1,
        snippet: "Verified directly via GSTN API: Active status with timely return filing history.",
        aiExplanation: "Statutory check passed. Direct government API verification confirmed identity and compliance."
      },
      {
        id: "req-4",
        name: "PAN Card & IT Return Validation",
        category: "Statutory",
        expected: "PAN verified & 3 Years ITR filings > ₹10 Cr avg turnover",
        extracted: "Verified, Avg Turnover ₹14.8 Cr",
        status: "PASS",
        risk: "LOW",
        confidence: 99,
        sourceDoc: "CA_Audited_Turnover_Cert.pdf",
        page: 1,
        snippet: "UDIN Verified: 26034182AAAA9912. 3-year turnover exceeds minimum tender requirement.",
        aiExplanation: "Financial turnover requirement verified through audited CA certificate with valid UDIN."
      },
      {
        id: "req-5",
        name: "Udyam MSE Registration Exemption",
        category: "Statutory",
        expected: "Valid Medium Enterprise category",
        extracted: "Medium Enterprise, Valid",
        status: "PASS",
        risk: "LOW",
        confidence: 97,
        sourceDoc: "Udyam_Certificate.pdf",
        page: 1,
        snippet: "Enterprise Classification: Medium. Major Activity: Manufacturing.",
        aiExplanation: "Enterprise classification matches tender eligibility criteria."
      }
    ]
  },
  {
    id: "B-102",
    bidId: "BID-2026-1025",
    name: "Apex Precision Valves Corp",
    pan: "BBBCB5678K",
    gstin: "27BBBCB5678K1ZR",
    udyam: "UDYAM-MH-01-0082371",
    submittedAt: "24 Aug 2026, 14:15",
    complianceScore: 94,
    riskLevel: "LOW",
    status: "UNDER_EVALUATION",
    financialBid: "₹ 14.10 Cr",
    localContentPercent: 62,
    tenderId: "T-1024",
    tenderNumber: "CPCL/2026/1024",
    organization: "Chennai Petroleum Corporation Limited",
    requirements: []
  },
  {
    id: "B-103",
    bidId: "BID-2026-1026",
    name: "Zenith Flow Controls Pvt Ltd",
    pan: "CCCCD9876P",
    gstin: "29CCCCD9876P1ZX",
    udyam: "UDYAM-KR-03-0045190",
    submittedAt: "23 Aug 2026, 19:30",
    complianceScore: 61,
    riskLevel: "HIGH",
    status: "COMPLIANCE_FAILED",
    financialBid: "₹ 12.90 Cr",
    localContentPercent: 35,
    tenderId: "T-1024",
    tenderNumber: "CPCL/2026/1024",
    organization: "Chennai Petroleum Corporation Limited",
    requirements: []
  },
  {
    id: "B-104",
    bidId: "BID-2026-1031",
    name: "TeleMetrics India Systems LLP",
    pan: "EEEEE5432R",
    gstin: "07EEEEE5432R1ZY",
    udyam: "UDYAM-DL-05-0012445",
    submittedAt: "22 Aug 2026, 11:20",
    complianceScore: 91,
    riskLevel: "LOW",
    status: "COMPLIANCE_PASSED",
    financialBid: "₹ 7.85 Cr",
    localContentPercent: 58,
    tenderId: "T-1031",
    tenderNumber: "IOCL/ENG/2026/89",
    organization: "Indian Oil Corporation Ltd",
    requirements: []
  },
  {
    id: "B-105",
    bidId: "BID-2026-1045",
    name: "Larsen & Turbo Heavy Engineering",
    pan: "FFFFF9876S",
    gstin: "27FFFFF9876S1ZQ",
    udyam: "UDYAM-MH-02-0099881",
    submittedAt: "20 Aug 2026, 16:50",
    complianceScore: 98,
    riskLevel: "LOW",
    status: "UNDER_EVALUATION",
    financialBid: "₹ 45.20 Cr",
    localContentPercent: 74,
    tenderId: "T-1045",
    tenderNumber: "ONGC/OFFSHORE/2026/112",
    organization: "Oil and Natural Gas Corporation",
    requirements: []
  }
];

export * from './adminData';
